### ISSUE TITLE
Add an ability to inject into x86_64 processes

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/task_vaccine#1]
- [x] Way to recognize whether an alien process is i386 or x86_64 (#4)  
- [x] Way to locate symbols within a remote process (#5)  
- [x] Configure an x86_64 remote thread for calling dlopen() within the target (#6)  
- [x] Configure an exception handler (#8)
