### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/task_vaccine#10]
##### Tests that should pass:
- [x] Inject `x86_64` payload from `x86_64` host into `x86_64` target  
- [x] Inject `FAT` payload from `x86_64` host into `x86_64` target  
- [x] Inject `i386` payload from `x86_64` host into `i386` target 
- [x] Inject `FAT` payload from `x86_64` host into `i386` target  
- [x] Inject `x86_64` payload from `i386` host into `x86_64` target  
- [x] Inject `FAT` payload from`i386` host into `x86_64` target  
- [x] Inject `i386` payload from `i386` host into `i386` target  
- [x] Inject `FAT` payload from `i386` host into `i386` target  
##### Tests that should **fail**:
- [x] Inject `i386` payload from `x86_64` host into `x86_64` target  
- [x] Inject `x86_64` payload from `x86_64` host into `i386` target  
- [x] Inject `i386` payload from `i386` host into `x86_64` target  
- [x] Inject `x86_64` payload from `i386` host into `i386` target
