### ISSUE TITLE
Add an ability to inject into i386 processes 

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/task_vaccine#2]
- [x] Way to recognize whether an alien process is i386 or x86_64 (#4)  
- [x] Way to locate symbols within a remote process (#5)  
- [x] Configure an i386 remote thread for calling dlopen() within the target  
- [x] Configure an exception handler (#8)
